### ISSUE TITLE
Pre-rendering error on windows

### ISSUE THREAD

**Issue by MrForExample** [zzzyuqing/DreamMat#10]
Thanks for solving [ray_tracing build issue on windows](https://github.com/zzzyuqing/DreamMat/issues/1) 👍 

**On windows 11, python 3.10, cuda 12.1, pytorch 2.3.1, Blender 3.2.2**

**cmd**
`python launch.py --config configs/dreammat.yaml --train --gradio --gpu 0  system.prompt_processor.prompt="A cute striped orange kitten" system.geometry.shape_init=mesh:load/shapes/objs/cat.obj trainer.max_steps=4000 system.geometry.shape_init_params=0.85 data.blender_generate=true`

**Error**
```bash
\DreamMat\threestudio_dreammat\threestudio\data\uncond.py", line 534, in loadrgb
    img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

**Reason**
Because Blender script can't create light rendering image. 

**All issues:**
- There are no rendered images in `DreamMat\threestudio_dreammat\outputs\dream_mat\A_cute_striped_kitten\pre_render\light`
- All depth images in `DreamMat\threestudio_dreammat\outputs\dream_mat\A_cute_striped_kitten\pre_render\depth` are almost pure black
![000](https://github.com/zzzyuqing/DreamMat/assets/62230687/380aa3d1-64bf-4d81-a48a-3de174fa8d59)

**Comment by MrForExample** [comment]
Solved issue by changing Line 447 in **blender_script_fixview.py** to `env_map = bpy.data.images.load(os.path.abspath(os.path.join(map_path,'map'+str(env+1), 'map'+str(env+1)+".exr")))`

**Comment by XZYW7** [comment]
Thank you for your exploring. You can remove the `stdout` keyword of `subprocess.run(command, shell=True, stdout=subprocess.DEVNULL)` in [` uncond.py `](https://github.com/zzzyuqing/DreamMat/blob/main/threestudio_dreammat/threestudio/data/uncond.py#529), Line 529 to view Blender’s detail output information for debugging.
For your issue, it is indeed caused by the directory of environment map on windows, and you can modify the path in [` uncond.py `](https://github.com/zzzyuqing/DreamMat/blob/main/threestudio_dreammat/threestudio/data/uncond.py#459), Line 459, or change the parameter of `--env_dir` to `{os.path.abspath(envmap_dir)}` in [` uncond.py `](https://github.com/zzzyuqing/DreamMat/blob/main/threestudio_dreammat/threestudio/data/uncond.py), Line520-526
```
command = (
                f"blender -b -P ./threestudio/data/blender_script_fixview.py --"
                f" --param_dir {pkl_path}"
                f" --env_dir {envmap_dir}"
                f" --output_dir {self.temp_image_save_dir}"
                f" --num_images {self.cfg.fix_view_num}"
            )
```
